<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用户表管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"学科管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"学科管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                        ],
                        "menu":"缴费记录管理",
                        "menuJump":"列表",
                        "tableName":"jiaofeijilu"
                    }
                ],
                "menu":"缴费记录管理"
            },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除",
			            ],
			            "menu":"设备管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"缴费类型管理",
                        "menuJump":"列表",
                        "tableName":"jiaofeileixing"
                    }
                ],
                "menu":"缴费类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                        ],
                        "menu":"设备借还管理",
                        "menuJump":"列表",
                        "tableName":"jiehuan"
                    }
                ],
                "menu":"设备借还管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
							"删除",
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"kaoqin"
                    }
                ],
                "menu":"考勤管理"
            }
            
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除",
	                    ],
	                    "menu":"成绩管理",
	                    "menuJump":"列表",
	                    "tableName":"chengji"
	                }
	            ],
	            "menu":"成绩管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除",
	                    ],
	                    "menu":"学科管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionary"
	                }
	            ],
	            "menu":"学科管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"缴费记录管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaofeijilu"
	                }
	            ],
	            "menu":"缴费记录管理"
	        },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "申请使用",
			            ],
			            "menu":"设备管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"缴费类型管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaofeileixing"
	                }
	            ],
	            "menu":"缴费类型管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "归还",
	                    ],
	                    "menu":"设备借还管理",
	                    "menuJump":"列表",
	                    "tableName":"jiehuan"
	                }
	            ],
	            "menu":"设备借还管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"签到",
	                    ],
	                    "menu":"考勤管理",
	                    "menuJump":"列表",
	                    "tableName":"kaoqin"
	                }
	            ],
	            "menu":"考勤管理"
	        }
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
